#travis configuration for coverage testing
language: c

# Compiler selection
compiler:
  - gcc

# Build steps
script: 
  - mkdir -p ${TRAVIS_BUILD_DIR}/build
  - cd ${TRAVIS_BUILD_DIR}/build
  - git clone --depth 1 https://github.com/llvm/llvm-project.git
  - rm -r llvm-project/clang-tools-extra/clang-tidy
  - ln -s `cd .. && pwd -L` llvm-project/clang-tools-extra/clang-tidy
  - cmake -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra" -DLLVM_USE_LINKER=gold -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" llvm-project/llvm
  - make -j4 clang-tidy
